name: Benchmark
on:
  push: {}
  workflow_dispatch: {}
  
permissions:
  contents: read
  id-token: write

jobs:
  build-with-ut:
    name: Build with UT
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin' 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          no-cache: true
          push: true
          tags: anuragharness/kafka:gha
      - name: Test UTs
        run: |
          gradle unitTest -PmaxParallelForks=32 -PignoreFailures=true
